### ISSUE TITLE
Camera random zoom out problem 

### ISSUE THREAD

**Issue by issamaf80** [oivio/Advanced-Camera-Manager#1]
Hello hope your doing well there in a bug in the asset that make in zoom out when pressing a random key sometime I posted a video in my profile page check it out and thanks

Here a video: https://www.youtube.com/watch?v=-llFVDQYYyE

**Comment by oivio** [comment]
thank you for reporting. Can you tell me what version do you use? is it the latest v2.1?

**Comment by issamaf80** [comment]
> thank you for reporting. Can you tell me what version do you use? is it the latest v2.1?

Hi yes am using the latest version am not so sure if its a bug or a problem with my project ( now when I click right mouse one time I get this bug) 
https://blueprintue.com/blueprint/d7_pctax/

**Comment by oivio** [comment]
It is not a bug. From your code, I can see that on Aim Input Press you do check if the player has equipped a weapon if so then you change the camera. But, if do not have then here you have a problem. Because on press camera do cache your last rotation mode but here it does not cache it so it does not know to what rotation mode it should go back to. 
I do not know if you use always velocity or look at direction but here you can change on input release from Aim to some default "LookingDirection" or "VelocityDireciton" or you can create enum variable that if the player does not have equipped weapon will save your current "rotation mode" and that saved rotation connect to input release camera. 

As example:
![fix](https://user-images.githubusercontent.com/38628851/124229450-ea7c3b00-db0d-11eb-9f7d-43ae3a852f8c.jpg)


Be aware. 
Advanced Camera Manager same as Advance Locomotion System it is not recommended for beginners.
